### ISSUE TITLE
Site-wide CSS for a consistent look and feel

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney_vue#25]

**Comment by kimchirice** [comment]
I will give this a go

**Comment by QjStout** [comment]
Thanks @kimchirice.
We may want to change the actual style rules later, but having it all set up so we can change it in one place would be great.

**Comment by kimchirice** [comment]
what ideas and suggestions you got, I remember you and @engramar discussed with @tanwui,  about have a design guide sorted or so, just wondering what's the status, or anything worth to share?? I am all ears

**Comment by QjStout** [comment]
It's on the list, but I just haven't had the time to get to it yet. It is coming though.

What I would like is to establish a colour scheme and have those colours available globally as something like:

* primary_colour
* secondary_colour
* alert_colour
* etc...

I was going to colour match the different shades of blue from the CodeSydney logo and then try out generating some colour schemes from that.

**Comment by tanwui** [comment]
Hi Codesydney/Codesydney, Qj, Kimchi,

Honestly, that's what I did when designing the Code Sydney style guide.
The blue colors with different shades in Code Sydney style guide are
color-picked from Code Sydney logo.
See below for your reference:

[image: StyleGuide.png]

Best regards,
Gabriel

**Comment by QjStout** [comment]
Hi @tanwui,

That link didn't come through.
I didn't know there was a colour pallet in the style guide.
I think some of your work might be missing from the wiki.
Would you be able to link me that again, or send it to me on Slack?

Thank you Gabriel.

**Comment by kimchirice** [comment]
I havent see any details in the design doc or figma links, I wanted to start with 
 - colors
 - fonts

for color, 
I had to manually pick those colors, could any of you @QjStout @tanwui @engramar who might has access to the details,  have a proof read and confirm below colors,

blue-color 
  1. #3cabde
  2. #99daed
  3. #46b5e3
  4. #6bceec
  5. #3e6887
  6. #41bde5
  7. #2f2f2f
  8. #489bd0
  9. #437da2
  10. #458dbf

bg-footer:
  11. #355878

bg-blue:
   12. #2b4c72

bg-Gray:
   13. #f8f9fa
   14. #8b8b8b

then font, I have a copy of root variables from current code.sydney site. 
```CSS
:root {
    --blue: #355878;
    --indigo: #6610f2;
    --purple: #6f42c1;
    --pink: #e83e8c;
    --red: #dc3545;
    --orange: #fd7e14;
    --yellow: #ffc107;
    --green: #28a745;
    --teal: #20c997;
    --cyan: #17a2b8;
    --white: #fff;
    --gray: #6c757d;
    --gray-dark: #343a40;
    --primary: #355878;
    --secondary: #6c757d;
    --success: #28a745;
    --info: #17a2b8;
    --warning: #ffc107;
    --danger: #dc3545;
    --light: #f8f9fa;
    --dark: #343a40;
    --breakpoint-xs: 0;
    --breakpoint-sm: 576px;
    --breakpoint-md: 768px;
    --breakpoint-lg: 992px;
    --breakpoint-xl: 1200px;

    --font-family-sans-serif: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    --font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
}
``` 

 I think we could start with  adding details blue shades to the :root, then setting the fonts up in CSS.
